### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by HexedHero** [fof1092/SpigotSearchEngine#5] opened 2022-10-16 22:05 UTC
All the plugin information is outdated.
For example, if you search "Pinata", you'll see the last update for PinataParty was Jul 14, 2022, which is incorrect.

**Comment by Ofir33** [comment] 2023-01-22 19:55
He still hasn't fixed it I think he left

**Comment by fof1092** [comment] 2023-10-22 22:33
The problem is fixed with version 3.0.1.

**Closed by fof1092** 2023-10-22 22:33 UTC
